// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbH8IjJKAe7NLPB2MO7IzOSJVP7qUgxms',
    appId: '1:854845124798:ios:1cde03c8344eb246f22eef',
    messagingSenderId: '854845124798',
    projectId: 'matlogbjj',
    storageBucket: 'matlogbjj.firebasestorage.app',
    iosBundleId: 'com.matlog.matlog',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuadOhU9dQ1oJNxWMsS2nZ1luUn80_lUY',
    appId: '1:854845124798:android:5e5d0ad3663eee21f22eef',
    messagingSenderId: '854845124798',
    projectId: 'matlogbjj',
    storageBucket: 'matlogbjj.firebasestorage.app',
  );
}
