// Mocks generated by Mockito 5.4.6 from annotations
// in matlog/test/unit/features/technique_library/technique_processing_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:matlog/src/features/authentication/domain/belt_info.dart'
    as _i6;
import 'package:matlog/src/features/profile/data/profile_repository.dart'
    as _i5;
import 'package:matlog/src/features/technique_library/data/technique_repository.dart'
    as _i2;
import 'package:matlog/src/features/technique_library/domain/technique.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TechniqueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTechniqueRepository extends _i1.Mock
    implements _i2.TechniqueRepository {
  @override
  _i3.Stream<List<_i4.Technique>> watchTechniques() =>
      (super.noSuchMethod(
            Invocation.method(#watchTechniques, []),
            returnValue: _i3.Stream<List<_i4.Technique>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.Technique>>.empty(),
          )
          as _i3.Stream<List<_i4.Technique>>);

  @override
  _i3.Future<_i4.Technique?> getTechnique(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTechnique, [id]),
            returnValue: _i3.Future<_i4.Technique?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Technique?>.value(),
          )
          as _i3.Future<_i4.Technique?>);

  @override
  _i3.Future<void> updateTechnique(_i4.Technique? technique) =>
      (super.noSuchMethod(
            Invocation.method(#updateTechnique, [technique]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> incrementRepetitions({
    required String? name,
    required String? position,
    required String? category,
    required int? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRepetitions, [], {
              #name: name,
              #position: position,
              #category: category,
              #amount: amount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i5.ProfileRepository {
  @override
  _i3.Stream<_i6.BeltInfo> watchUserBeltInfo() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserBeltInfo, []),
            returnValue: _i3.Stream<_i6.BeltInfo>.empty(),
            returnValueForMissingStub: _i3.Stream<_i6.BeltInfo>.empty(),
          )
          as _i3.Stream<_i6.BeltInfo>);

  @override
  _i3.Stream<_i7.DocumentSnapshot<Object?>> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i3.Stream<_i7.DocumentSnapshot<Object?>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i7.DocumentSnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i7.DocumentSnapshot<Object?>>);

  @override
  _i3.Future<void> updateBeltInfo(_i6.BeltInfo? beltInfo) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeltInfo, [beltInfo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateViewedMissions(List<String>? missionIds) =>
      (super.noSuchMethod(
            Invocation.method(#updateViewedMissions, [missionIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile({
    required String? name,
    required String? academy,
    required _i6.BeltInfo? beltInfo,
    List<int>? trainingDays,
    String? trainingTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #academy: academy,
              #beltInfo: beltInfo,
              #trainingDays: trainingDays,
              #trainingTime: trainingTime,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSchedule({
    required List<int>? trainingDays,
    required String? trainingTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSchedule, [], {
              #trainingDays: trainingDays,
              #trainingTime: trainingTime,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> ensureUserTag() =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserTag, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMissionStats({
    int? submissions = 0,
    int? passes = 0,
    int? sweeps = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMissionStats, [], {
              #submissions: submissions,
              #passes: passes,
              #sweeps: sweeps,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
