// Mocks generated by Mockito 5.4.6 from annotations
// in matlog/test/widget/onboarding_login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:flutter/material.dart' as _i10;
import 'package:matlog/src/features/authentication/data/auth_repository.dart'
    as _i3;
import 'package:matlog/src/features/authentication/domain/belt_info.dart'
    as _i5;
import 'package:matlog/src/features/notifications/data/notification_service.dart'
    as _i9;
import 'package:matlog/src/features/profile/data/profile_repository.dart'
    as _i6;
import 'package:matlog/src/features/tutorial/data/tutorial_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Stream<_i2.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i4.Stream<_i2.User?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.User?>.empty(),
          )
          as _i4.Stream<_i2.User?>);

  @override
  _i4.Future<void> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createUserWithEmailAndPassword(
    String? email,
    String? password,
    _i5.BeltInfo? beltInfo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
              beltInfo,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<void> convertAnonymousToPermanent(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#convertAnonymousToPermanent, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i6.ProfileRepository {
  @override
  _i4.Stream<_i5.BeltInfo> watchUserBeltInfo() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserBeltInfo, []),
            returnValue: _i4.Stream<_i5.BeltInfo>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.BeltInfo>.empty(),
          )
          as _i4.Stream<_i5.BeltInfo>);

  @override
  _i4.Stream<_i7.DocumentSnapshot<Object?>> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Stream<_i7.DocumentSnapshot<Object?>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i7.DocumentSnapshot<Object?>>.empty(),
          )
          as _i4.Stream<_i7.DocumentSnapshot<Object?>>);

  @override
  _i4.Future<void> updateBeltInfo(_i5.BeltInfo? beltInfo) =>
      (super.noSuchMethod(
            Invocation.method(#updateBeltInfo, [beltInfo]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateViewedMissions(List<String>? missionIds) =>
      (super.noSuchMethod(
            Invocation.method(#updateViewedMissions, [missionIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfile({
    required String? name,
    required String? academy,
    required _i5.BeltInfo? beltInfo,
    List<int>? trainingDays,
    String? trainingTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #academy: academy,
              #beltInfo: beltInfo,
              #trainingDays: trainingDays,
              #trainingTime: trainingTime,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSchedule({
    required List<int>? trainingDays,
    required String? trainingTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSchedule, [], {
              #trainingDays: trainingDays,
              #trainingTime: trainingTime,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> ensureUserTag() =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserTag, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateMissionStats({
    int? submissions = 0,
    int? passes = 0,
    int? sweeps = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMissionStats, [], {
              #submissions: submissions,
              #passes: passes,
              #sweeps: sweeps,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TutorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialRepository extends _i1.Mock
    implements _i8.TutorialRepository {
  @override
  _i4.Future<bool> isTutorialCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#isTutorialCompleted, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> markTutorialCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#markTutorialCompleted, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetTutorial() =>
      (super.noSuchMethod(
            Invocation.method(#resetTutorial, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> schedulePostTrainingNotification({
    required _i10.TimeOfDay? time,
    required List<int>? weekdays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#schedulePostTrainingNotification, [], {
              #time: time,
              #weekdays: weekdays,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
