// Mocks generated by Mockito
import 'package:mockito/annotations.dart';
import 'package:matlog/src/features/technique_library/data/technique_repository.dart';

@GenerateMocks([TechniqueRepository])
void main() {}
